// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func Balance(balance float64) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"hu\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Egyenleg - SmartOrders</title><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\"><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script></head><body class=\"bg-gray-100\"><nav class=\"bg-green-600 p-4\"><div class=\"container mx-auto flex flex-col md:flex-row justify-between items-center\"><a href=\"/\" class=\"text-white text-2xl font-bold mb-4 md:mb-0\">SmartOrders</a><div class=\"flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-4\"><a href=\"/order\" class=\"text-white text-center\">Rendelés</a> <a href=\"/status\" class=\"text-white text-center\">Státusz</a> <a href=\"/balance\" class=\"text-white text-center\">Egyenleg</a> <a href=\"/logout\" class=\"text-white text-center\">Kijelentkezés</a></div></div></nav><div class=\"container mx-auto px-4 mt-8\"><div class=\"max-w-2xl mx-auto\"><h1 class=\"text-3xl font-bold mb-8 text-gray-800\">Egyenleg kezelése</h1><div class=\"bg-white rounded-lg shadow-md p-6 mb-6\"><div class=\"text-xl mb-4\"><span class=\"font-semibold text-gray-700\">Jelenlegi egyenleg:</span> <span class=\"text-green-600 font-bold ml-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.2f", balance))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/balance.templ`, Line: 35, Col: 98}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" Ft</span></div></div><div class=\"bg-white rounded-lg shadow-md p-6\"><h2 class=\"text-xl font-semibold mb-4 text-gray-800\">Egyenleg feltöltése</h2><form hx-post=\"/balance\" hx-target=\"#result\" class=\"space-y-4\"><div><label for=\"amount\" class=\"block text-sm font-medium text-gray-700 mb-2\">Feltöltendő összeg (Ft)</label> <input type=\"number\" id=\"amount\" name=\"amount\" min=\"0\" step=\"100\" class=\"w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-green-500 focus:border-green-500\" required></div><button type=\"submit\" class=\"w-full bg-green-600 text-white py-2 px-4 rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 transition-colors\">Feltöltés</button></form><div id=\"result\" class=\"mt-4 text-center\"></div></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
