@startuml SmartOrders
actor Customer
participant SmartOrders
actor BackOffice
participant Courier

BackOffice -> SmartOrders : Updates items
Customer -> SmartOrders : New order
SmartOrders -> BackOffice : Order request

BackOffice --> BackOffice : Validating order
BackOffice -> SmartOrders : Accepts order
SmartOrders --> Customer : Accepts order\nstatus: ORDERED

alt Insufficient Balance
    SmartOrders --> Customer : Display insufficient balance message
    Customer -> SmartOrders : Tops up virtual balance
    SmartOrders --> Customer : Updates balance
    Customer -> SmartOrders : Retries order
    SmartOrders -> BackOffice : Balance sync
    SmartOrders -> BackOffice : Generates order request
    BackOffice --> BackOffice : Validating order
    BackOffice -> SmartOrders : Accept order
    BackOffice -> SmartOrders : Balance update
    SmartOrders -> Customer : Confirms order
end

SmartOrders --> Customer : Decrease virtual balance
BackOffice --> Customer : Approves order\nstatus: ORDERED
BackOffice -> BackOffice : Import order
BackOffice -> BackOffice : Pack parcel
BackOffice --> SmartOrders : Update parcel number\nstatus: AT_COURIER
BackOffice -> Courier : Hand over parcel

Courier -> Customer : Deliver parcel with tracking number
@enduml
